// Every piece of interface text, one table per language. English is the reference: a key
// missing from another table falls back to it. A text that depends on a number has one
// entry per plural form, `key#one` and `key#other`; languages without plural forms only
// have `#other`. `{name}` marks a value filled in at run time and must stay as it is.
// Words Lightroom also uses follow Lightroom's own wording, see tools/lightroom-terms.json.
// French has a no-break space before : ; ? and inside « »; keep it when editing.
export const STRINGS = {
  en: {
    'home.title': 'Library',
    'home.refresh': 'Refresh',
    'home.refreshing': 'Refreshing',
    'home.search': 'Search folders and collections',
    'home.searchClear': 'Clear search',
    'home.toTop': 'Back to top',
    'home.recent': 'Recently opened',
    'home.folders': 'Folders',
    'home.collections': 'Collections',
    'home.noMatch': 'No matching folders or collections',
    'home.emptyCatalog': 'This catalog has no folders or collections yet',
    'home.noListOffline': 'Offline, and this device has not saved the catalog list yet. It appears by itself once the computer is reachable',
    'home.noList': 'The catalog list cannot be read right now. It appears by itself once that is resolved',
    'source.cache': 'Cache',
    'source.cachedCount': 'Cached {n}',
    'source.cached': 'Cached',
    'source.collapse': 'Collapse {name}',
    'source.expand': 'Expand {name}',
    'sort.folders': 'Folder order',
    'sort.nameDesc': 'Name ↓',
    'sort.nameAsc': 'Name ↑',
    'sort.import': 'Import order',
    'sort.photos': 'Photo order',
    'sort.timeAsc': 'Capture time ↑',
    'sort.timeDesc': 'Capture time ↓',
    'sort.fileName': 'File name',
    'common.back': 'Back',
    'common.withSize': '{what}, about {size}',
    'common.twoSentences': '{first} {second}',
    'count.photos#one': '{n} photo',
    'count.photos#other': '{n} photos',
    'count.previews#one': '{n} cached preview',
    'count.previews#other': '{n} cached previews',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.languageAuto': 'Auto (device language)',
    'settings.culling': 'Culling',
    'settings.quality': 'Preview quality',
    'quality.auto': 'Auto (by device)',
    'quality.std': 'Standard',
    'quality.hd': 'High',
    'settings.advance': 'Go to the next photo after a mark',
    'advance.flag': 'Pick and reject only',
    'advance.any': 'Any mark',
    'advance.never': 'Never',
    'settings.defaultFilter': 'Show when a folder opens',
    'settings.leftHand': 'Left-hand mode (controls on the left in landscape)',
    'settings.offline': 'Offline cache',
    'settings.autoCache': 'Cache unmarked photos automatically at home',
    'settings.autoLimit': 'Automatic cache limit',
    'settings.counting': 'Counting',
    'settings.clearCache': 'Clear cache',
    'settings.clearNote': 'Removes only the previews and photo lists stored on this device. Photos in Lightroom and marks that have not synced are not affected.',
    'settings.clearConfirm': 'Clear the previews and photo lists cached on this device? Marks that have not synced are not affected.',
    'settings.connection': 'Connection',
    'settings.qrAlt': 'QR code of the connection address',
    'settings.qrNote': 'On another device signed in to the same Tailscale account, scan this code to open the app.',
    'settings.homeScreenTip': 'In Safari, choose “Add to Home Screen” and open the app from its icon: it runs full screen, and iOS will not clear the offline data after 7 days without a visit.',
    'info.address': 'Address',
    'info.lrConnected': 'Connected',
    'info.lrOff': 'Not running',
    'info.unreachable': 'Computer unreachable',
    'info.network': 'Network',
    'net.home': 'Home network (direct)',
    'net.away': 'Away, or through a relay',
    'net.unknown': 'Cannot tell',
    'info.unknown': 'Unknown',
    'info.pending': 'Marks waiting to sync',
    'info.pendingCount': '{n}',
    'info.openedAs': 'Opened as',
    'info.standalone': 'Home Screen app',
    'info.browser': 'Browser',
    'info.version': 'Version',
    'filter.label': 'Filter',
    'filter.unmarked': 'Unmarked',
    'filter.all': 'All',
    'mark.pick': 'Pick',
    'mark.reject': 'Reject',
    'mark.unflag': 'Flag removed',
    'mark.stars#one': '{n} star',
    'mark.stars#other': '{n} stars',
    'mark.noRating': 'Rating cleared',
    'mark.noLabel': 'Label cleared',
    'label.red': 'Red',
    'label.yellow': 'Yellow',
    'label.green': 'Green',
    'label.blue': 'Blue',
    'label.purple': 'Purple',
    'viewer.prev': 'Previous photo',
    'viewer.next': 'Next photo',
    'viewer.loading': 'Loading',
    'viewer.noUnmarked': 'No unmarked photos here',
    'viewer.noPhotos': 'No photos here',
    'viewer.notCached': 'This photo is not cached. It shows once the computer is reachable; you can still mark or skip it',
    'viewer.previewFailed': 'The preview failed to load. Tap the middle of the photo to retry',
    'viewer.folderNotCached': 'This folder is not cached yet. It opens once the computer is reachable',
    'viewer.marksHidden': 'Marks hidden',
    'viewer.marksShown': 'Marks shown',
    'viewer.opFailed': '{name}: {reason}',
    'cache.close': 'Close',
    'cache.unmarked': 'Cache unmarked',
    'cache.all': 'Cache all',
    'cache.cancel': 'Cancel',
    'cache.keepOpen': 'Previews are stored on this device only. Keep this page in the foreground and the screen unlocked while caching; if it is interrupted, tap again and it continues where it stopped.',
    'cache.loading': 'Reading the photo list',
    'cache.loadFailed': 'Could not read the list: {reason}',
    'cache.summary': '{photos}. Quality: {quality}.',
    'cache.away': 'This device is not on the home network, or that cannot be determined; the download may use mobile data.',
    'cache.progress': 'Cached {done} / {total}',
    'cache.endFailed': 'Cached {cached}, failed {failed}. Tap again to retry',
    'cache.endCancelled': 'Cancelled. Cached {cached}',
    'cache.endQuota': 'The device is out of storage. Cached {cached}',
    'cache.endInterrupted': 'Connection lost. Cached {cached}. Tap again later to continue',
    'cache.allCached': '{photos}, all cached',
    'cache.partial': '{photos}, {left} to download, about {size}',
    'status.network': 'Offline',
    'status.lr_offline': 'Lightroom is not running',
    'status.lr_busy': 'Lightroom is busy',
    'status.lr_timeout': 'Lightroom is not answering',
    'status.waiting': '{status}, {n} waiting to sync',
    'error.lr_offline': 'Lightroom is not running, or the plug-in is not loaded',
    'error.lr_busy': 'Lightroom is busy (a dialog may be open). Try again shortly',
    'error.lr_timeout': 'Lightroom took too long to answer. Try again shortly',
    'error.photo_not_found': 'This photo is no longer in the catalog',
    'error.source_not_found': 'This folder or collection no longer exists',
    'error.network': 'Cannot reach the computer. Check the network and Tailscale',
    'error.plugin_error': 'The Lightroom plug-in reported an error. See the plug-in log for details',
    'error.invalid_size': 'Invalid preview size',
    'error.preview_timeout': 'The preview took too long to build. Try again',
    'error.bad_preview': 'The preview data is damaged. Try again',
    'error.generic': 'That did not work. Try again',
  },
  'zh-CN': {
    'home.title': '图库',
    'home.refresh': '刷新',
    'home.refreshing': '刷新中',
    'home.search': '搜索文件夹或收藏夹',
    'home.searchClear': '清除搜索',
    'home.toTop': '回到顶部',
    'home.recent': '最近打开',
    'home.folders': '文件夹',
    'home.collections': '收藏夹',
    'home.noMatch': '没有匹配的文件夹或收藏夹',
    'home.emptyCatalog': '这个目录里还没有文件夹或收藏夹',
    'home.noListOffline': '离线，这台设备上还没有保存过目录列表。联网后会自动出现',
    'home.noList': '暂时读不到目录列表，恢复后会自动出现',
    'source.cache': '缓存',
    'source.cachedCount': '已缓存 {n}',
    'source.cached': '已缓存',
    'source.collapse': '折叠 {name}',
    'source.expand': '展开 {name}',
    'sort.folders': '文件夹排序',
    'sort.nameDesc': '名称 ↓',
    'sort.nameAsc': '名称 ↑',
    'sort.import': '导入顺序',
    'sort.photos': '照片顺序',
    'sort.timeAsc': '拍摄时间 ↑',
    'sort.timeDesc': '拍摄时间 ↓',
    'sort.fileName': '文件名',
    'common.back': '返回',
    'common.withSize': '{what}，约 {size}',
    'common.twoSentences': '{first}{second}',
    'count.photos#other': '{n} 张',
    'count.previews#other': '已缓存预览 {n} 张',
    'settings.title': '设置',
    'settings.language': '语言',
    'settings.languageAuto': '自动（跟随设备）',
    'settings.culling': '筛片',
    'settings.quality': '预览清晰度',
    'quality.auto': '自动（按设备）',
    'quality.std': '标准',
    'quality.hd': '高清',
    'settings.advance': '打标后跳到下一张',
    'advance.flag': '仅留用和排除',
    'advance.any': '任何标记',
    'advance.never': '不跳转',
    'settings.defaultFilter': '进入文件夹时显示',
    'settings.leftHand': '左手模式（横屏时操作栏在左侧）',
    'settings.offline': '离线缓存',
    'settings.autoCache': '在家时自动缓存未标记照片',
    'settings.autoLimit': '自动缓存上限',
    'settings.counting': '正在统计',
    'settings.clearCache': '清除缓存',
    'settings.clearNote': '只清除这台设备上的预览图和照片列表。Lightroom 里的照片和还没同步的标记都不受影响。',
    'settings.clearConfirm': '清除这台设备上缓存的预览图和照片列表？还没同步的标记不受影响。',
    'settings.connection': '连接',
    'settings.qrAlt': '连接地址的二维码',
    'settings.qrNote': '另一台设备登录同一个 Tailscale 账号后，扫这个码就能打开。',
    'settings.homeScreenTip': '建议在 Safari 里"添加到主屏幕"后从图标打开：可以全屏使用，离线数据也不会因为 7 天没有访问而被系统清理。',
    'info.address': '地址',
    'info.lrConnected': '已连接',
    'info.lrOff': '未运行',
    'info.unreachable': '连不上电脑',
    'info.network': '网络位置',
    'net.home': '家里的网络（直连）',
    'net.away': '不在家，或经过中继',
    'net.unknown': '无法判断',
    'info.unknown': '未知',
    'info.pending': '待同步标记',
    'info.pendingCount': '{n} 条',
    'info.openedAs': '打开方式',
    'info.standalone': '主屏幕应用',
    'info.browser': '浏览器',
    'info.version': '版本',
    'filter.label': '筛选',
    'filter.unmarked': '未标记',
    'filter.all': '全部',
    'mark.pick': '留用',
    'mark.reject': '排除',
    'mark.unflag': '取消旗标',
    'mark.stars#other': '{n} 星',
    'mark.noRating': '清除星级',
    'mark.noLabel': '清除色标',
    'label.red': '红色',
    'label.yellow': '黄色',
    'label.green': '绿色',
    'label.blue': '蓝色',
    'label.purple': '紫色',
    'viewer.prev': '上一张',
    'viewer.next': '下一张',
    'viewer.loading': '加载中',
    'viewer.noUnmarked': '这里没有未标记的照片',
    'viewer.noPhotos': '这里没有照片',
    'viewer.notCached': '这张照片没有缓存，联网后可以查看；现在仍可标记或跳过',
    'viewer.previewFailed': '预览加载失败，点照片中间重试',
    'viewer.folderNotCached': '这个文件夹还没有缓存，联网后才能打开',
    'viewer.marksHidden': '已隐藏标记',
    'viewer.marksShown': '已显示标记',
    'viewer.opFailed': '{name}：{reason}',
    'cache.close': '关闭',
    'cache.unmarked': '缓存未标记',
    'cache.all': '缓存全部',
    'cache.cancel': '取消',
    'cache.keepOpen': '预览图只保存在这台设备上。缓存期间请保持这个页面在前台，不要锁屏；中断后再点一次会从断点继续。',
    'cache.loading': '正在读取照片列表',
    'cache.loadFailed': '读取失败：{reason}',
    'cache.summary': '共 {photos}，{quality}清晰度。',
    'cache.away': '当前不在家里的网络，或无法判断，下载可能会用到蜂窝流量。',
    'cache.progress': '已缓存 {done} / {total}',
    'cache.endFailed': '已缓存 {cached} 张，{failed} 张失败，再点一次可以重试',
    'cache.endCancelled': '已取消，已缓存 {cached} 张',
    'cache.endQuota': '设备存储空间不足，已缓存 {cached} 张',
    'cache.endInterrupted': '连接中断，已缓存 {cached} 张，稍后再点一次可以继续',
    'cache.allCached': '{photos}，已全部缓存',
    'cache.partial': '{photos}，还差 {left} 张，约 {size}',
    'status.network': '离线',
    'status.lr_offline': 'Lightroom 未运行',
    'status.lr_busy': 'Lightroom 正忙',
    'status.lr_timeout': 'Lightroom 响应超时',
    'status.waiting': '{status}，待同步 {n} 条',
    'error.lr_offline': 'Lightroom 未运行，或增效工具没有加载',
    'error.lr_busy': 'Lightroom 正忙（可能开着对话框），请稍后再试',
    'error.lr_timeout': 'Lightroom 响应超时，请稍后再试',
    'error.photo_not_found': '这张照片已不在目录里',
    'error.source_not_found': '这个文件夹或收藏夹已不存在',
    'error.network': '连不上电脑，请检查网络和 Tailscale',
    'error.plugin_error': 'Lightroom 增效工具出错，详情见增效工具日志',
    'error.invalid_size': '预览尺寸无效',
    'error.preview_timeout': '预览生成超时，请重试',
    'error.bad_preview': '预览数据异常，请重试',
    'error.generic': '操作失败，请重试',
  },
  ja: {
    'home.title': 'ライブラリ',
    'home.refresh': '更新',
    'home.refreshing': '更新中',
    'home.search': 'フォルダーやコレクションを検索',
    'home.searchClear': '検索をクリア',
    'home.toTop': '先頭へ戻る',
    'home.recent': '最近開いた項目',
    'home.folders': 'フォルダー',
    'home.collections': 'コレクション',
    'home.noMatch': '一致するフォルダーやコレクションがありません',
    'home.emptyCatalog': 'このカタログにはまだフォルダーやコレクションがありません',
    'home.noListOffline': 'オフラインです。このデバイスにはまだカタログの一覧が保存されていません。接続が戻ると自動的に表示されます',
    'home.noList': '現在カタログの一覧を読み込めません。復旧すると自動的に表示されます',
    'source.cache': 'キャッシュ',
    'source.cachedCount': 'キャッシュ済み {n}',
    'source.cached': 'キャッシュ済み',
    'source.collapse': '{name} を折りたたむ',
    'source.expand': '{name} を展開',
    'sort.folders': 'フォルダーの並び順',
    'sort.nameDesc': '名前 ↓',
    'sort.nameAsc': '名前 ↑',
    'sort.import': '読み込み順',
    'sort.photos': '写真の並び順',
    'sort.timeAsc': '撮影日時 ↑',
    'sort.timeDesc': '撮影日時 ↓',
    'sort.fileName': 'ファイル名',
    'common.back': '戻る',
    'common.withSize': '{what}、約 {size}',
    'common.twoSentences': '{first}{second}',
    'count.photos#other': '{n} 枚',
    'count.previews#other': 'キャッシュ済みプレビュー {n} 枚',
    'settings.title': '設定',
    'settings.language': '言語',
    'settings.languageAuto': '自動（デバイスの言語）',
    'settings.culling': 'セレクト',
    'settings.quality': 'プレビュー画質',
    'quality.auto': '自動（デバイスに合わせる）',
    'quality.std': '標準',
    'quality.hd': '高画質',
    'settings.advance': 'マーク後に次の写真へ進む',
    'advance.flag': '採用と除外のみ',
    'advance.any': 'すべてのマーク',
    'advance.never': '進まない',
    'settings.defaultFilter': 'フォルダーを開いたときの表示',
    'settings.leftHand': '左手モード（横向きでは操作バーを左側に表示）',
    'settings.offline': 'オフラインキャッシュ',
    'settings.autoCache': '自宅ではマークなしの写真を自動でキャッシュ',
    'settings.autoLimit': '自動キャッシュの上限',
    'settings.counting': '集計中',
    'settings.clearCache': 'キャッシュを消去',
    'settings.clearNote': 'このデバイスに保存されたプレビューと写真の一覧だけを消去します。Lightroom 内の写真と未同期のマークには影響しません。',
    'settings.clearConfirm': 'このデバイスにキャッシュされたプレビューと写真の一覧を消去しますか？未同期のマークには影響しません。',
    'settings.connection': '接続',
    'settings.qrAlt': '接続アドレスの QR コード',
    'settings.qrNote': '同じ Tailscale アカウントにログインした別のデバイスでこのコードを読み取ると開けます。',
    'settings.homeScreenTip': 'Safari で「ホーム画面に追加」を選び、アイコンから開くことをおすすめします。全画面で使え、7 日間アクセスがなくてもオフラインデータが iOS に消去されません。',
    'info.address': 'アドレス',
    'info.lrConnected': '接続済み',
    'info.lrOff': '起動していません',
    'info.unreachable': 'コンピューターに接続できません',
    'info.network': 'ネットワーク',
    'net.home': '自宅のネットワーク（直接接続）',
    'net.away': '外出先、またはリレー経由',
    'net.unknown': '判定できません',
    'info.unknown': '不明',
    'info.pending': '未同期のマーク',
    'info.pendingCount': '{n} 件',
    'info.openedAs': '開き方',
    'info.standalone': 'ホーム画面のアプリ',
    'info.browser': 'ブラウザー',
    'info.version': 'バージョン',
    'filter.label': 'フィルター',
    'filter.unmarked': 'マークなし',
    'filter.all': 'すべて',
    'mark.pick': '採用',
    'mark.reject': '除外',
    'mark.unflag': 'フラグを削除',
    'mark.stars#other': '{n} つ星',
    'mark.noRating': 'レーティングを削除',
    'mark.noLabel': 'カラーラベルを削除',
    'label.red': 'レッド',
    'label.yellow': 'イエロー',
    'label.green': 'グリーン',
    'label.blue': 'ブルー',
    'label.purple': 'パープル',
    'viewer.prev': '前の写真',
    'viewer.next': '次の写真',
    'viewer.loading': '読み込み中',
    'viewer.noUnmarked': 'マークなしの写真はありません',
    'viewer.noPhotos': '写真がありません',
    'viewer.notCached': 'この写真はキャッシュされていません。接続が戻ると表示されます。このままマークやスキップはできます',
    'viewer.previewFailed': 'プレビューを読み込めませんでした。写真の中央をタップして再試行してください',
    'viewer.folderNotCached': 'このフォルダーはまだキャッシュされていません。接続が戻ると開けます',
    'viewer.marksHidden': 'マークを非表示',
    'viewer.marksShown': 'マークを表示',
    'viewer.opFailed': '{name}：{reason}',
    'cache.close': '閉じる',
    'cache.unmarked': 'マークなしをキャッシュ',
    'cache.all': 'すべてキャッシュ',
    'cache.cancel': 'キャンセル',
    'cache.keepOpen': 'プレビューはこのデバイスにのみ保存されます。キャッシュ中はこのページを前面に表示したまま、画面をロックしないでください。中断した場合は、もう一度タップすると続きから再開します。',
    'cache.loading': '写真の一覧を読み込み中',
    'cache.loadFailed': '読み込みに失敗しました：{reason}',
    'cache.summary': '全 {photos}。画質：{quality}。',
    'cache.away': '自宅のネットワークに接続していないか、判定できません。ダウンロードにモバイルデータ通信を使う場合があります。',
    'cache.progress': 'キャッシュ済み {done} / {total}',
    'cache.endFailed': 'キャッシュ済み {cached} 枚、失敗 {failed} 枚。もう一度タップすると再試行します',
    'cache.endCancelled': 'キャンセルしました。キャッシュ済み {cached} 枚',
    'cache.endQuota': 'デバイスの空き容量が不足しています。キャッシュ済み {cached} 枚',
    'cache.endInterrupted': '接続が切れました。キャッシュ済み {cached} 枚。あとでもう一度タップすると続きから再開します',
    'cache.allCached': '{photos}、すべてキャッシュ済み',
    'cache.partial': '{photos}、残り {left} 枚、約 {size}',
    'status.network': 'オフライン',
    'status.lr_offline': 'Lightroom が起動していません',
    'status.lr_busy': 'Lightroom がビジー状態です',
    'status.lr_timeout': 'Lightroom の応答がありません',
    'status.waiting': '{status}、未同期 {n} 件',
    'error.lr_offline': 'Lightroom が起動していないか、プラグインが読み込まれていません',
    'error.lr_busy': 'Lightroom がビジー状態です（ダイアログが開いている可能性があります）。しばらくしてからもう一度お試しください',
    'error.lr_timeout': 'Lightroom の応答がタイムアウトしました。しばらくしてからもう一度お試しください',
    'error.photo_not_found': 'この写真はすでにカタログにありません',
    'error.source_not_found': 'このフォルダーまたはコレクションはすでに存在しません',
    'error.network': 'コンピューターに接続できません。ネットワークと Tailscale を確認してください',
    'error.plugin_error': 'Lightroom プラグインでエラーが発生しました。詳しくはプラグインのログを確認してください',
    'error.invalid_size': 'プレビューのサイズが無効です',
    'error.preview_timeout': 'プレビューの生成がタイムアウトしました。もう一度お試しください',
    'error.bad_preview': 'プレビューのデータが壊れています。もう一度お試しください',
    'error.generic': '操作に失敗しました。もう一度お試しください',
  },
  de: {
    'home.title': 'Bibliothek',
    'home.refresh': 'Neu laden',
    'home.refreshing': 'Lädt',
    'home.search': 'Ordner und Sammlungen suchen',
    'home.searchClear': 'Suche löschen',
    'home.toTop': 'Nach oben',
    'home.recent': 'Zuletzt geöffnet',
    'home.folders': 'Ordner',
    'home.collections': 'Sammlungen',
    'home.noMatch': 'Keine passenden Ordner oder Sammlungen',
    'home.emptyCatalog': 'Dieser Katalog enthält noch keine Ordner oder Sammlungen',
    'home.noListOffline': 'Offline, und auf diesem Gerät ist noch keine Katalogliste gespeichert. Sie erscheint von selbst, sobald der Computer erreichbar ist',
    'home.noList': 'Die Katalogliste kann gerade nicht gelesen werden. Sie erscheint von selbst, sobald das wieder geht',
    'source.cache': 'Cachen',
    'source.cachedCount': 'Im Cache: {n}',
    'source.cached': 'Im Cache',
    'source.collapse': '{name} einklappen',
    'source.expand': '{name} ausklappen',
    'sort.folders': 'Ordner sortieren',
    'sort.nameDesc': 'Name ↓',
    'sort.nameAsc': 'Name ↑',
    'sort.import': 'Importreihenfolge',
    'sort.photos': 'Fotos sortieren',
    'sort.timeAsc': 'Aufnahmezeit ↑',
    'sort.timeDesc': 'Aufnahmezeit ↓',
    'sort.fileName': 'Dateiname',
    'common.back': 'Zurück',
    'common.withSize': '{what}, etwa {size}',
    'common.twoSentences': '{first} {second}',
    'count.photos#one': '{n} Foto',
    'count.photos#other': '{n} Fotos',
    'count.previews#one': '{n} Vorschau im Cache',
    'count.previews#other': '{n} Vorschauen im Cache',
    'settings.title': 'Einstellungen',
    'settings.language': 'Sprache',
    'settings.languageAuto': 'Automatisch (Gerätesprache)',
    'settings.culling': 'Bildauswahl',
    'settings.quality': 'Vorschauqualität',
    'quality.auto': 'Automatisch (je nach Gerät)',
    'quality.std': 'Standard',
    'quality.hd': 'Hoch',
    'settings.advance': 'Nach einer Kennzeichnung zum nächsten Foto',
    'advance.flag': 'Nur Markiert und Abgelehnt',
    'advance.any': 'Jede Kennzeichnung',
    'advance.never': 'Nie',
    'settings.defaultFilter': 'Beim Öffnen eines Ordners anzeigen',
    'settings.leftHand': 'Linkshändermodus (Bedienleiste im Querformat links)',
    'settings.offline': 'Offline-Cache',
    'settings.autoCache': 'Offene Fotos zu Hause automatisch cachen',
    'settings.autoLimit': 'Obergrenze für automatisches Cachen',
    'settings.counting': 'Wird gezählt',
    'settings.clearCache': 'Cache leeren',
    'settings.clearNote': 'Entfernt nur die Vorschauen und Fotolisten auf diesem Gerät. Fotos in Lightroom und noch nicht synchronisierte Kennzeichnungen bleiben unberührt.',
    'settings.clearConfirm': 'Die auf diesem Gerät gecachten Vorschauen und Fotolisten entfernen? Noch nicht synchronisierte Kennzeichnungen bleiben unberührt.',
    'settings.connection': 'Verbindung',
    'settings.qrAlt': 'QR-Code der Verbindungsadresse',
    'settings.qrNote': 'Auf einem anderen Gerät, das im selben Tailscale-Konto angemeldet ist, diesen Code scannen, um die App zu öffnen.',
    'settings.homeScreenTip': 'In Safari „Zum Home-Bildschirm“ wählen und die App über ihr Symbol öffnen: Sie läuft dann im Vollbild, und iOS löscht die Offline-Daten nicht nach 7 Tagen ohne Besuch.',
    'info.address': 'Adresse',
    'info.lrConnected': 'Verbunden',
    'info.lrOff': 'Läuft nicht',
    'info.unreachable': 'Computer nicht erreichbar',
    'info.network': 'Netzwerk',
    'net.home': 'Heimnetz (direkt)',
    'net.away': 'Unterwegs oder über ein Relay',
    'net.unknown': 'Nicht feststellbar',
    'info.unknown': 'Unbekannt',
    'info.pending': 'Wartende Kennzeichnungen',
    'info.pendingCount': '{n}',
    'info.openedAs': 'Geöffnet als',
    'info.standalone': 'App vom Home-Bildschirm',
    'info.browser': 'Browser',
    'info.version': 'Version',
    'filter.label': 'Filter',
    'filter.unmarked': 'Offen',
    'filter.all': 'Alle',
    'mark.pick': 'Markiert',
    'mark.reject': 'Abgelehnt',
    'mark.unflag': 'Markierung entfernt',
    'mark.stars#one': '{n} Stern',
    'mark.stars#other': '{n} Sterne',
    'mark.noRating': 'Bewertung entfernt',
    'mark.noLabel': 'Farbmarkierung entfernt',
    'label.red': 'Rot',
    'label.yellow': 'Gelb',
    'label.green': 'Grün',
    'label.blue': 'Blau',
    'label.purple': 'Lila',
    'viewer.prev': 'Vorheriges Foto',
    'viewer.next': 'Nächstes Foto',
    'viewer.loading': 'Lädt',
    'viewer.noUnmarked': 'Hier gibt es keine offenen Fotos',
    'viewer.noPhotos': 'Hier gibt es keine Fotos',
    'viewer.notCached': 'Dieses Foto ist nicht im Cache. Es erscheint, sobald der Computer erreichbar ist; kennzeichnen oder überspringen geht trotzdem',
    'viewer.previewFailed': 'Die Vorschau konnte nicht geladen werden. Zum Wiederholen in die Fotomitte tippen',
    'viewer.folderNotCached': 'Dieser Ordner ist noch nicht im Cache. Er lässt sich öffnen, sobald der Computer erreichbar ist',
    'viewer.marksHidden': 'Kennzeichnungen aus',
    'viewer.marksShown': 'Kennzeichnungen an',
    'viewer.opFailed': '{name}: {reason}',
    'cache.close': 'Schließen',
    'cache.unmarked': 'Offene Fotos cachen',
    'cache.all': 'Alle cachen',
    'cache.cancel': 'Abbrechen',
    'cache.keepOpen': 'Vorschauen werden nur auf diesem Gerät gespeichert. Während des Cachens diese Seite im Vordergrund lassen und den Bildschirm nicht sperren; nach einer Unterbrechung erneut tippen, dann geht es an derselben Stelle weiter.',
    'cache.loading': 'Fotoliste wird gelesen',
    'cache.loadFailed': 'Liste konnte nicht gelesen werden: {reason}',
    'cache.summary': '{photos}. Qualität: {quality}.',
    'cache.away': 'Dieses Gerät ist nicht im Heimnetz, oder das lässt sich nicht feststellen; der Download kann mobile Daten verbrauchen.',
    'cache.progress': 'Im Cache: {done} / {total}',
    'cache.endFailed': 'Im Cache: {cached}, fehlgeschlagen: {failed}. Zum Wiederholen erneut tippen',
    'cache.endCancelled': 'Abgebrochen. Im Cache: {cached}',
    'cache.endQuota': 'Der Gerätespeicher ist voll. Im Cache: {cached}',
    'cache.endInterrupted': 'Verbindung unterbrochen. Im Cache: {cached}. Später erneut tippen, um fortzufahren',
    'cache.allCached': '{photos}, alle im Cache',
    'cache.partial': '{photos}, {left} fehlen noch, etwa {size}',
    'status.network': 'Offline',
    'status.lr_offline': 'Lightroom läuft nicht',
    'status.lr_busy': 'Lightroom ist beschäftigt',
    'status.lr_timeout': 'Lightroom antwortet nicht',
    'status.waiting': '{status}, noch zu synchronisieren: {n}',
    'error.lr_offline': 'Lightroom läuft nicht, oder das Zusatzmodul ist nicht geladen',
    'error.lr_busy': 'Lightroom ist beschäftigt (vielleicht ist ein Dialog offen). Bitte gleich noch einmal versuchen',
    'error.lr_timeout': 'Lightroom hat zu lange nicht geantwortet. Bitte gleich noch einmal versuchen',
    'error.photo_not_found': 'Dieses Foto ist nicht mehr im Katalog',
    'error.source_not_found': 'Dieser Ordner oder diese Sammlung existiert nicht mehr',
    'error.network': 'Der Computer ist nicht erreichbar. Bitte Netzwerk und Tailscale prüfen',
    'error.plugin_error': 'Das Lightroom-Zusatzmodul meldet einen Fehler. Details stehen im Protokoll des Zusatzmoduls',
    'error.invalid_size': 'Ungültige Vorschaugröße',
    'error.preview_timeout': 'Die Vorschau hat zu lange gebraucht. Bitte noch einmal versuchen',
    'error.bad_preview': 'Die Vorschaudaten sind beschädigt. Bitte noch einmal versuchen',
    'error.generic': 'Das hat nicht geklappt. Bitte noch einmal versuchen',
  },
  fr: {
    'home.title': 'Bibliothèque',
    'home.refresh': 'Actualiser',
    'home.refreshing': 'Actualisation',
    'home.search': 'Rechercher des dossiers et des collections',
    'home.searchClear': 'Effacer la recherche',
    'home.toTop': 'Haut de la liste',
    'home.recent': 'Ouverts récemment',
    'home.folders': 'Dossiers',
    'home.collections': 'Collections',
    'home.noMatch': 'Aucun dossier ni collection correspondant',
    'home.emptyCatalog': 'Ce catalogue ne contient encore aucun dossier ni collection',
    'home.noListOffline': 'Hors ligne, et cet appareil n’a pas encore enregistré la liste du catalogue. Elle apparaîtra d’elle-même dès que l’ordinateur sera joignable',
    'home.noList': 'La liste du catalogue ne peut pas être lue pour le moment. Elle apparaîtra d’elle-même une fois le problème résolu',
    'source.cache': 'Mettre en cache',
    'source.cachedCount': 'En cache : {n}',
    'source.cached': 'En cache',
    'source.collapse': 'Réduire {name}',
    'source.expand': 'Développer {name}',
    'sort.folders': 'Ordre des dossiers',
    'sort.nameDesc': 'Nom ↓',
    'sort.nameAsc': 'Nom ↑',
    'sort.import': 'Ordre d’importation',
    'sort.photos': 'Ordre des photos',
    'sort.timeAsc': 'Heure de capture ↑',
    'sort.timeDesc': 'Heure de capture ↓',
    'sort.fileName': 'Nom de fichier',
    'common.back': 'Retour',
    'common.withSize': '{what}, environ {size}',
    'common.twoSentences': '{first} {second}',
    'count.photos#one': '{n} photo',
    'count.photos#other': '{n} photos',
    'count.previews#one': '{n} aperçu en cache',
    'count.previews#other': '{n} aperçus en cache',
    'settings.title': 'Réglages',
    'settings.language': 'Langue',
    'settings.languageAuto': 'Automatique (langue de l’appareil)',
    'settings.culling': 'Tri',
    'settings.quality': 'Qualité des aperçus',
    'quality.auto': 'Automatique (selon l’appareil)',
    'quality.std': 'Standard',
    'quality.hd': 'Élevée',
    'settings.advance': 'Passer à la photo suivante après un marquage',
    'advance.flag': 'Retenue et rejetée seulement',
    'advance.any': 'Tout marquage',
    'advance.never': 'Jamais',
    'settings.defaultFilter': 'Afficher à l’ouverture d’un dossier',
    'settings.leftHand': 'Mode gaucher (commandes à gauche en paysage)',
    'settings.offline': 'Cache hors ligne',
    'settings.autoCache': 'Mettre en cache automatiquement les photos à trier à la maison',
    'settings.autoLimit': 'Limite du cache automatique',
    'settings.counting': 'Calcul en cours',
    'settings.clearCache': 'Vider le cache',
    'settings.clearNote': 'Supprime uniquement les aperçus et les listes de photos enregistrés sur cet appareil. Les photos dans Lightroom et les marquages non synchronisés ne sont pas touchés.',
    'settings.clearConfirm': 'Supprimer les aperçus et les listes de photos mis en cache sur cet appareil ? Les marquages non synchronisés ne sont pas touchés.',
    'settings.connection': 'Connexion',
    'settings.qrAlt': 'Code QR de l’adresse de connexion',
    'settings.qrNote': 'Sur un autre appareil connecté au même compte Tailscale, scanner ce code pour ouvrir l’application.',
    'settings.homeScreenTip': 'Dans Safari, choisir « Sur l’écran d’accueil » et ouvrir l’application depuis son icône : elle s’affiche en plein écran, et iOS n’efface pas les données hors ligne après 7 jours sans visite.',
    'info.address': 'Adresse',
    'info.lrConnected': 'Connecté',
    'info.lrOff': 'Non lancé',
    'info.unreachable': 'Ordinateur injoignable',
    'info.network': 'Réseau',
    'net.home': 'Réseau domestique (direct)',
    'net.away': 'À l’extérieur, ou via un relais',
    'net.unknown': 'Indéterminé',
    'info.unknown': 'Inconnu',
    'info.pending': 'Marquages en attente',
    'info.pendingCount': '{n}',
    'info.openedAs': 'Ouvert comme',
    'info.standalone': 'App de l’écran d’accueil',
    'info.browser': 'Navigateur',
    'info.version': 'Version',
    'filter.label': 'Filtre',
    'filter.unmarked': 'À trier',
    'filter.all': 'Toutes',
    'mark.pick': 'Retenue',
    'mark.reject': 'Rejetée',
    'mark.unflag': 'Marqueur supprimé',
    'mark.stars#one': '{n} étoile',
    'mark.stars#other': '{n} étoiles',
    'mark.noRating': 'Note supprimée',
    'mark.noLabel': 'Libellé supprimé',
    'label.red': 'Rouge',
    'label.yellow': 'Jaune',
    'label.green': 'Vert',
    'label.blue': 'Bleu',
    'label.purple': 'Violet',
    'viewer.prev': 'Photo précédente',
    'viewer.next': 'Photo suivante',
    'viewer.loading': 'Chargement',
    'viewer.noUnmarked': 'Aucune photo à trier ici',
    'viewer.noPhotos': 'Aucune photo ici',
    'viewer.notCached': 'Cette photo n’est pas en cache. Elle s’affichera dès que l’ordinateur sera joignable ; il reste possible de la marquer ou de la passer',
    'viewer.previewFailed': 'L’aperçu n’a pas pu être chargé. Toucher le centre de la photo pour réessayer',
    'viewer.folderNotCached': 'Ce dossier n’est pas encore en cache. Il s’ouvrira dès que l’ordinateur sera joignable',
    'viewer.marksHidden': 'Marquages masqués',
    'viewer.marksShown': 'Marquages affichés',
    'viewer.opFailed': '{name} : {reason}',
    'cache.close': 'Fermer',
    'cache.unmarked': 'Mettre en cache les photos à trier',
    'cache.all': 'Tout mettre en cache',
    'cache.cancel': 'Annuler',
    'cache.keepOpen': 'Les aperçus sont enregistrés uniquement sur cet appareil. Pendant la mise en cache, garder cette page au premier plan et l’écran déverrouillé ; en cas d’interruption, toucher à nouveau pour reprendre là où elle s’est arrêtée.',
    'cache.loading': 'Lecture de la liste des photos',
    'cache.loadFailed': 'Impossible de lire la liste : {reason}',
    'cache.summary': '{photos}. Qualité : {quality}.',
    'cache.away': 'Cet appareil n’est pas sur le réseau domestique, ou cela ne peut pas être déterminé ; le téléchargement peut utiliser des données mobiles.',
    'cache.progress': 'En cache : {done} / {total}',
    'cache.endFailed': 'En cache : {cached}, échecs : {failed}. Toucher à nouveau pour réessayer',
    'cache.endCancelled': 'Annulé. En cache : {cached}',
    'cache.endQuota': 'L’espace de stockage de l’appareil est plein. En cache : {cached}',
    'cache.endInterrupted': 'Connexion interrompue. En cache : {cached}. Toucher à nouveau plus tard pour continuer',
    'cache.allCached': '{photos}, toutes en cache',
    'cache.partial': '{photos}, {left} à télécharger, environ {size}',
    'status.network': 'Hors ligne',
    'status.lr_offline': 'Lightroom n’est pas lancé',
    'status.lr_busy': 'Lightroom est occupé',
    'status.lr_timeout': 'Lightroom ne répond pas',
    'status.waiting': '{status}, {n} en attente de synchronisation',
    'error.lr_offline': 'Lightroom n’est pas lancé, ou le module externe n’est pas chargé',
    'error.lr_busy': 'Lightroom est occupé (une boîte de dialogue est peut-être ouverte). Réessayer dans un instant',
    'error.lr_timeout': 'Lightroom a mis trop de temps à répondre. Réessayer dans un instant',
    'error.photo_not_found': 'Cette photo n’est plus dans le catalogue',
    'error.source_not_found': 'Ce dossier ou cette collection n’existe plus',
    'error.network': 'Impossible de joindre l’ordinateur. Vérifier le réseau et Tailscale',
    'error.plugin_error': 'Le module externe Lightroom a signalé une erreur. Voir son journal pour les détails',
    'error.invalid_size': 'Taille d’aperçu non valide',
    'error.preview_timeout': 'La création de l’aperçu a pris trop de temps. Réessayer',
    'error.bad_preview': 'Les données de l’aperçu sont endommagées. Réessayer',
    'error.generic': 'L’opération a échoué. Réessayer',
  },
  es: {
    'home.title': 'Biblioteca',
    'home.refresh': 'Actualizar',
    'home.refreshing': 'Actualizando',
    'home.search': 'Buscar carpetas y colecciones',
    'home.searchClear': 'Borrar búsqueda',
    'home.toTop': 'Volver arriba',
    'home.recent': 'Abiertos recientemente',
    'home.folders': 'Carpetas',
    'home.collections': 'Colecciones',
    'home.noMatch': 'Ninguna carpeta o colección coincide',
    'home.emptyCatalog': 'Este catálogo aún no tiene carpetas ni colecciones',
    'home.noListOffline': 'Sin conexión, y este dispositivo aún no ha guardado la lista del catálogo. Aparecerá sola cuando se pueda acceder al ordenador',
    'home.noList': 'La lista del catálogo no se puede leer en este momento. Aparecerá sola cuando se resuelva',
    'source.cache': 'Guardar en caché',
    'source.cachedCount': 'En caché: {n}',
    'source.cached': 'En caché',
    'source.collapse': 'Contraer {name}',
    'source.expand': 'Expandir {name}',
    'sort.folders': 'Orden de carpetas',
    'sort.nameDesc': 'Nombre ↓',
    'sort.nameAsc': 'Nombre ↑',
    'sort.import': 'Orden de importación',
    'sort.photos': 'Orden de fotos',
    'sort.timeAsc': 'Hora de captura ↑',
    'sort.timeDesc': 'Hora de captura ↓',
    'sort.fileName': 'Nombre de archivo',
    'common.back': 'Atrás',
    'common.withSize': '{what}, aprox. {size}',
    'common.twoSentences': '{first} {second}',
    'count.photos#one': '{n} foto',
    'count.photos#other': '{n} fotos',
    'count.previews#one': '{n} previsualización en caché',
    'count.previews#other': '{n} previsualizaciones en caché',
    'settings.title': 'Ajustes',
    'settings.language': 'Idioma',
    'settings.languageAuto': 'Automático (idioma del dispositivo)',
    'settings.culling': 'Revisión',
    'settings.quality': 'Calidad de previsualización',
    'quality.auto': 'Automática (según el dispositivo)',
    'quality.std': 'Estándar',
    'quality.hd': 'Alta',
    'settings.advance': 'Pasar a la foto siguiente tras una marca',
    'advance.flag': 'Solo selección y rechazo',
    'advance.any': 'Cualquier marca',
    'advance.never': 'Nunca',
    'settings.defaultFilter': 'Mostrar al abrir una carpeta',
    'settings.leftHand': 'Modo zurdo (controles a la izquierda en horizontal)',
    'settings.offline': 'Caché sin conexión',
    'settings.autoCache': 'Guardar en caché automáticamente las fotos sin marcar en casa',
    'settings.autoLimit': 'Límite de la caché automática',
    'settings.counting': 'Contando',
    'settings.clearCache': 'Vaciar caché',
    'settings.clearNote': 'Solo elimina las previsualizaciones y las listas de fotos guardadas en este dispositivo. Las fotos de Lightroom y las marcas sin sincronizar no se ven afectadas.',
    'settings.clearConfirm': '¿Eliminar las previsualizaciones y las listas de fotos en caché de este dispositivo? Las marcas sin sincronizar no se ven afectadas.',
    'settings.connection': 'Conexión',
    'settings.qrAlt': 'Código QR de la dirección de conexión',
    'settings.qrNote': 'En otro dispositivo con la misma cuenta de Tailscale, escanee este código para abrir la aplicación.',
    'settings.homeScreenTip': 'En Safari, elija «Añadir a pantalla de inicio» y abra la aplicación desde su icono: se muestra a pantalla completa, e iOS no borra los datos sin conexión tras 7 días sin visitas.',
    'info.address': 'Dirección',
    'info.lrConnected': 'Conectado',
    'info.lrOff': 'No está abierto',
    'info.unreachable': 'Ordenador inaccesible',
    'info.network': 'Red',
    'net.home': 'Red de casa (directa)',
    'net.away': 'Fuera de casa, o a través de un repetidor',
    'net.unknown': 'No se puede determinar',
    'info.unknown': 'Desconocido',
    'info.pending': 'Marcas pendientes',
    'info.pendingCount': '{n}',
    'info.openedAs': 'Abierto como',
    'info.standalone': 'App de la pantalla de inicio',
    'info.browser': 'Navegador',
    'info.version': 'Versión',
    'filter.label': 'Filtro',
    'filter.unmarked': 'Sin marcar',
    'filter.all': 'Todas',
    'mark.pick': 'Selección',
    'mark.reject': 'Rechazo',
    'mark.unflag': 'Indicador quitado',
    'mark.stars#one': '{n} estrella',
    'mark.stars#other': '{n} estrellas',
    'mark.noRating': 'Clasificación quitada',
    'mark.noLabel': 'Etiqueta quitada',
    'label.red': 'Rojo',
    'label.yellow': 'Amarillo',
    'label.green': 'Verde',
    'label.blue': 'Azul',
    'label.purple': 'Púrpura',
    'viewer.prev': 'Foto anterior',
    'viewer.next': 'Foto siguiente',
    'viewer.loading': 'Cargando',
    'viewer.noUnmarked': 'Aquí no hay fotos sin marcar',
    'viewer.noPhotos': 'Aquí no hay fotos',
    'viewer.notCached': 'Esta foto no está en caché. Se mostrará cuando se pueda acceder al ordenador; aun así se puede marcar o saltar',
    'viewer.previewFailed': 'No se pudo cargar la previsualización. Toque el centro de la foto para reintentar',
    'viewer.folderNotCached': 'Esta carpeta aún no está en caché. Se abrirá cuando se pueda acceder al ordenador',
    'viewer.marksHidden': 'Marcas ocultas',
    'viewer.marksShown': 'Marcas visibles',
    'viewer.opFailed': '{name}: {reason}',
    'cache.close': 'Cerrar',
    'cache.unmarked': 'Guardar en caché las fotos sin marcar',
    'cache.all': 'Guardar todo en caché',
    'cache.cancel': 'Cancelar',
    'cache.keepOpen': 'Las previsualizaciones solo se guardan en este dispositivo. Durante el guardado, mantenga esta página en primer plano y la pantalla desbloqueada; si se interrumpe, toque de nuevo y continuará donde se quedó.',
    'cache.loading': 'Leyendo la lista de fotos',
    'cache.loadFailed': 'No se pudo leer la lista: {reason}',
    'cache.summary': '{photos}. Calidad: {quality}.',
    'cache.away': 'Este dispositivo no está en la red de casa, o no se puede determinar; la descarga puede usar datos móviles.',
    'cache.progress': 'En caché: {done} / {total}',
    'cache.endFailed': 'En caché: {cached}, con error: {failed}. Toque de nuevo para reintentar',
    'cache.endCancelled': 'Cancelado. En caché: {cached}',
    'cache.endQuota': 'El almacenamiento del dispositivo está lleno. En caché: {cached}',
    'cache.endInterrupted': 'Conexión interrumpida. En caché: {cached}. Toque de nuevo más tarde para continuar',
    'cache.allCached': '{photos}, todas en caché',
    'cache.partial': '{photos}, faltan {left}, aprox. {size}',
    'status.network': 'Sin conexión',
    'status.lr_offline': 'Lightroom no está abierto',
    'status.lr_busy': 'Lightroom está ocupado',
    'status.lr_timeout': 'Lightroom no responde',
    'status.waiting': '{status}, {n} pendientes de sincronizar',
    'error.lr_offline': 'Lightroom no está abierto, o el plugin no está cargado',
    'error.lr_busy': 'Lightroom está ocupado (puede que haya un cuadro de diálogo abierto). Inténtelo de nuevo en un momento',
    'error.lr_timeout': 'Lightroom tardó demasiado en responder. Inténtelo de nuevo en un momento',
    'error.photo_not_found': 'Esta foto ya no está en el catálogo',
    'error.source_not_found': 'Esta carpeta o colección ya no existe',
    'error.network': 'No se puede acceder al ordenador. Compruebe la red y Tailscale',
    'error.plugin_error': 'El plugin de Lightroom ha informado de un error. Consulte su registro para ver los detalles',
    'error.invalid_size': 'Tamaño de previsualización no válido',
    'error.preview_timeout': 'La previsualización tardó demasiado en crearse. Inténtelo de nuevo',
    'error.bad_preview': 'Los datos de la previsualización están dañados. Inténtelo de nuevo',
    'error.generic': 'No ha funcionado. Inténtelo de nuevo',
  },
};
